# Travis Build File
language: java
jdk:
  - openjdk11

#matrix:
#  include:
#    - jdk: openjdk10
#      before_install:
##        - rm "${JAVA_HOME}/lib/security/cacerts"
#        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

before_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: mvn clean compile test

notifications:
  email:
    - indra.basak1@gmail.com
  on_success: change
  on_failure: always
  use_notice: true

