# use a random unassigned HTTP port by scanning for free port
server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plai


# For Spring Actuator /info endpoint
info:
    artifact: book
    name: book
    description: Book Service
    version: 1.0.0

security:
  auth:
    users:
      userA:
        password: pwdA
      userB:
        password: pwdB

#Exposes Spring actuator endpoints
management:
#  security:
#    enabled: true
#    roles: ACTUATOR
#    roles: SUPERUSER
  health:
    diskspace:
      enabled: true
    db:
      enabled: true
    details:
      enabled: true
    application:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:jtds:sqlserver://%%mysystemName%%/;instance=mydb;domain=DHC;trusted=true;
#  security:
#    user:
#      name: admin
#      password: secret