# use a random unassigned HTTP port by scanning for free port
server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plai


# For Spring Actuator /info endpoint
info:
    artifact: book
    name: book
    description: Book Service
    version: 1.0.0

security:
  user:
    name: admin
    password: secret
  auth:
    users:
      userA:
        password: pwdA
      userB:
        password: pwdB

#Exposes Spring actuator endpoints
management:
  context-path: /manage
  security:
    enabled: true
#    roles: ACTUATOR
#    roles: SUPERUSER

spring:
  datasource:
    url: jdbc:jtds:sqlserver://%%mysystemName%%/;instance=mydb;domain=DHC;trusted=true;