# use a random unassigned HTTP port by scanning for free port
server:
  port: 8080


# For Spring Actuator /info endpoint
info:
    artifact: book
    name: book
    description: Book Service
    version: 1.0.0

datasource:
  validationQuery: SELECT 1
  initialSize: 1
  maxActive: 3
  testWhileIdle: true
  testOnBorrow: true

jpa:
  show-sql: true
  format_sql: true
  properties:
    org:
      hibernate:
        flushMode: AUTO